name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We'd love to hear your ideas.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve?
      placeholder: "I'm trying to analyze data from HubSpot but there's no connector for it..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: |
        A HubSpot connector that:
        - Authenticates via OAuth or API key
        - Extracts contacts, deals, and companies
        - Maps to the standard NormalizedRecord format
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any other approaches you've considered?

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - New Connector
        - New Vertical
        - CLI
        - Metrics
        - Entity Resolution
        - Anomaly Detection
        - MCP Server
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: willing-to-implement
    attributes:
      label: Would you be willing to implement this?
      options:
        - "Yes, I'd like to submit a PR"
        - "I can help but would need guidance"
        - "No, just suggesting"
    validations:
      required: true
